import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {once} from 'node:events';import {createHash} from 'node:crypto';import {request} from 'node:https';import {createServer} from 'node:net';import {mobile} from '../src/mobile.ts';
test('HTTPS auth secure cookies CSRF uploads and private runner bridge',async()=>{
const root=mkdtempSync(join(tmpdir(),'mobile-test-'));let web;const calls=[];const sock=join(root,'control.sock');const bridge=createServer(s=>{s.on('data',b=>{calls.push(JSON.parse(b.toString()));s.end(JSON.stringify({ok:true,result:[]})+'\n');});});
try{execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',join(root,'key'),' -out'.trim(),join(root,'cert'),'-days','1','-subj','/CN=localhost'],{stdio:'ignore'});bridge.listen(sock);await once(bridge,'listening');web=mobile({key:join(root,'key'),cert:join(root,'cert'),accessHash:createHash('sha256').update('test-access').digest('hex'),origin:'https://localhost',host:'127.0.0.1',port:0,socket:sock,attachments:join(root,'images'),publicDir:new URL('../public',import.meta.url).pathname});await once(web,'listening');
const req=(path,data,cookie,origin='https://localhost')=>new Promise((resolve,reject)=>{const r=request({hostname:'127.0.0.1',port:web.address().port,path,method:data?'POST':'GET',rejectUnauthorized:false,headers:{...(data?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{Cookie:cookie}:{})}},res=>{let b='';res.on('data',x=>b+=x);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:b}));});r.on('error',reject);r.end(data?JSON.stringify(data):undefined);});
assert.equal((await req('/api/projects')).status,401);assert.equal((await req('/api/tasks')).status,401);assert.equal((await req('/api/login',{key:'wrong'})).status,401);const login=await req('/api/login',{key:'test-access'});assert.equal(login.status,200);const cookie=login.headers['set-cookie'][0];assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);assert.equal((await req('/api/tasks',null,cookie)).status,200);
assert.equal((await req('/api/action',{op:'approve',id:'x'},cookie,'https://evil.example')).status,403);assert.equal((await req('/api/action',{op:'shell'},cookie)).status,400);assert.equal((await req('/api/action',{op:'project-checks',id:'default',dependencies:'/tmp'},cookie)).status,400);assert.equal((await req('/api/action',{op:'project-register',name:'unsafe',repo:'/tmp'},cookie)).status,400);await req('/api/projects',null,cookie);assert.equal(calls.at(-1).op,'projects');await req('/api/projects/default/conversations',null,cookie);assert.equal(calls.at(-1).project,'default');await req('/api/action',{op:'project-create',name:'Example'},cookie);assert.equal(calls.at(-1).op,'project-create');
await req('/api/operations',null,cookie);assert.equal(calls.at(-1).op,'operations');
assert.equal((await req('/api/account')).status,401);
assert.equal((await req('/api/account',{action:'start',adapter:'claude',operation:'login'},cookie,'https://evil.example')).status,403);
assert.equal((await req('/api/action',{op:'account-start',owner:'spoofed',adapter:'claude',action:'login'},cookie)).status,400);
assert.equal((await req('/api/account',{action:'start',adapter:'shell',operation:'login'},cookie)).status,400);
await req('/api/account',{action:'start',adapter:'claude',operation:'login',owner:'spoofed'},cookie);assert.equal(calls.at(-1).op,'account-start');assert.match(calls.at(-1).owner,/^[a-f0-9]{64}$/);const accountOwner=calls.at(-1).owner;
await req('/api/account',null,cookie);assert.equal(calls.at(-1).owner,accountOwner);assert.equal(calls.at(-1).op,'account-session');
await req('/api/account',{action:'code',session:'fixture',code:'one-time-code'},cookie);assert.equal(calls.at(-1).op,'account-code');assert.equal(calls.at(-1).code,'one-time-code');
const otherLogin=await req('/api/login',{key:'test-access'});await req('/api/account',null,otherLogin.headers['set-cookie'][0]);assert.notEqual(calls.at(-1).owner,accountOwner);
assert.equal((await req('/api/upload',{name:'bad',data:Buffer.from('not an image at all').toString('base64')},cookie)).status,400);
const upload=await req('/api/upload',{name:'test.png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='},cookie);assert.equal(upload.status,201);const img=JSON.parse(upload.body);assert.equal((await req('/api/images/'+img.id)).status,401);assert.equal((await req('/api/images/'+img.id,null,cookie)).status,200);
await req('/api/action',{op:'create',adapter:'codex',prompt:'test',attachments:[img.id]},cookie);assert.equal(calls.at(-1).attachments[0],img.id);await req('/api/logout',{},cookie);assert.equal((await req('/api/tasks',null,cookie)).status,401);
}finally{if(web){web.closeAllConnections();await new Promise(r=>web.close(r));}await new Promise(r=>bridge.close(r));rmSync(root,{recursive:true,force:true});}
});
