import {spawn,execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {stripVTControlCharacters} from 'node:util';
import {cursorPermission,cursorVersion} from './cursor-policy.ts';
export async function runCursor(binary:string,mode:string,prompt:string,output:(text:string)=>void= text=>process.stdout.write(text)){
 if(!['ask','edit'].includes(mode))throw Error('Unsupported Cursor mode');
 if(execFileSync(binary,['--version'],{encoding:'utf8',timeout:10000,stdio:['ignore','pipe','ignore']}).trim()!==cursorVersion)throw Error('Cursor CLI version changed. Install the tested release.');
 const child=spawn(binary,['--sandbox','enabled',...(mode==='ask'?['--mode','ask']:[]),'acp'],{stdio:['pipe','pipe','ignore']});
 let sequence=0,buffer='',session='',bytes=0,closed=false,denied=false;const pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 const fail=(message:string)=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error(message));}pending.clear();};
 const send=(value:any)=>child.stdin.write(JSON.stringify({jsonrpc:'2.0',...value})+'\n');
 const request=(method:string,params:any)=>new Promise<any>((resolve,reject)=>{if(closed){reject(Error('Cursor stopped unexpectedly'));return;}const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(Error('Cursor response timed out'));child.kill('SIGKILL');},method==='session/prompt'?15*60*1000:60000);pending.set(id,{resolve,reject,timer});send({id,method,params});});
 child.stdin.on('error',()=>fail('Cursor connection closed'));child.on('error',()=>fail('Cursor could not start'));child.on('close',()=>{closed=true;fail('Cursor stopped unexpectedly');});
 child.stdout.on('data',chunk=>{buffer+=chunk.toString();if(buffer.length>2_000_000){fail('Cursor response exceeded the limit');child.kill('SIGKILL');return;}let end;while((end=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,end);buffer=buffer.slice(end+1);if(!line.trim())continue;let message:any;try{message=JSON.parse(line);if(!message||typeof message!=='object'||Array.isArray(message)||message.jsonrpc!=='2.0')throw Error();}catch{fail('Cursor returned invalid protocol data');child.kill('SIGKILL');return;}
  if(message.method){
   if(message.id!==undefined){if(message.method==='session/request_permission'){const decision=cursorPermission(message.params,mode,process.cwd(),session);if(decision.outcome.outcome!=='selected')denied=true;send({id:message.id,result:decision});}else{denied=true;send({id:message.id,error:{code:-32601,message:'Unsupported by agentd policy'}});}continue;}
   if(message.method==='session/update'&&message.params?.sessionId===session){const update=message.params.update;if(update?.sessionUpdate==='tool_call_update'&&update.status==='failed')denied=true;if(update?.sessionUpdate==='agent_message_chunk'&&update.content?.type==='text'&&typeof update.content.text==='string'){bytes+=Buffer.byteLength(update.content.text);if(bytes>2_000_000){fail('Cursor output exceeded the limit');child.kill('SIGKILL');return;}output(stripVTControlCharacters(update.content.text));}}
  }else{const p=pending.get(message.id);if(p){clearTimeout(p.timer);pending.delete(message.id);message.error?p.reject(Error('Cursor request failed. Check account status, account limits and the supported work mode.')):p.resolve(message.result);}}
 }});
 const stop=()=>{if(session&&!closed)send({method:'session/cancel',params:{sessionId:session}});child.kill('SIGTERM');};process.on('SIGTERM',stop);process.on('SIGINT',stop);
 try{const init=await request('initialize',{protocolVersion:1,clientCapabilities:{fs:{readTextFile:false,writeTextFile:false},terminal:false},clientInfo:{name:'agentd',version:'0.18.0'}});if(init?.protocolVersion!==1)throw Error('Unsupported Cursor protocol');await request('authenticate',{methodId:'cursor_login'});const created=await request('session/new',{cwd:process.cwd(),mcpServers:[]});if(typeof created?.sessionId!=='string')throw Error('Cursor did not create a session');session=created.sessionId;await request('session/set_mode',{sessionId:session,modeId:mode==='edit'?'agent':'ask'});const result=await request('session/prompt',{sessionId:session,prompt:[{type:'text',text:prompt}]});if(result?.stopReason!=='end_turn'||denied)throw Error(denied?'Cursor requested a tool outside the approved file-only policy. No broader permission was granted.':'Cursor did not finish this turn');}
 finally{process.off('SIGTERM',stop);process.off('SIGINT',stop);child.stdin.end();child.kill('SIGKILL');fail('Cursor session ended');}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){try{await runCursor(process.argv[2],process.argv[3],process.argv[4]);}catch(e){console.error((e as Error).message);process.exitCode=1;}}
