import {spawn} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {createHash} from 'node:crypto';import {githubURL,branchName,type RepositoryGit} from './repositories.ts';
export type PullAPI=(destination:string,branch:string,base:string,data:{title:string;body:string}|null,signal:AbortSignal)=>Promise<any>;
export function githubPullAPI(state:string,profile:string,executable='/usr/local/bin/gh'):PullAPI{return async(destination,branch,base,data,signal)=>{
 const slug=githubURL(destination).slice('https://github.com/'.length,-4),owner=slug.split('/')[0],endpoint='repos/'+slug+'/pulls'+(data?'':'?state=all&head='+encodeURIComponent(owner+':'+branch)+'&base='+encodeURIComponent(base)+'&per_page=100');
 const home=mkdtempSync(join(state,'git-home-'));try{return await new Promise((resolve,reject)=>{
  const args=['api','--hostname','github.com','-H','Accept: application/vnd.github+json','-H','X-GitHub-Api-Version: 2026-03-10','--method',data?'POST':'GET',endpoint,...(data?['--input','-']:[])];
  const child=spawn(executable,args,{cwd:home,env:{HOME:home,GH_CONFIG_DIR:profile,GH_HOST:'github.com',GH_PROMPT_DISABLED:'1',PATH:'/usr/local/bin:/usr/bin:/bin'},detached:true,stdio:['pipe','pipe','ignore']});let output='',stopped=false;
  const stop=()=>{stopped=true;if(child.pid)try{process.kill(-child.pid,'SIGKILL');}catch{}};signal.addEventListener('abort',stop,{once:true});const timer=setTimeout(stop,60000);if(signal.aborted)stop();child.on('error',()=>{});child.stdin.on('error',()=>{});child.stdout.on('data',v=>{output+=v.toString();if(output.length>2_000_000)stop();});child.stdin.end(data?JSON.stringify({...data,head:branch,base,draft:true}):undefined);
  child.on('close',code=>{clearTimeout(timer);signal.removeEventListener('abort',stop);if(child.pid)try{process.kill(-child.pid,'SIGKILL');}catch{};try{if(code!==0||stopped)throw Error();resolve(JSON.parse(output));}catch{reject(Error('GitHub could not confirm the pull-request operation. Check your GitHub connection and repository permissions, then preview again to reconcile any completed work.'));}});
 });}finally{rmSync(home,{recursive:true,force:true});}
};}
export type PublishPlan={destination:string;base:string;baseSha:string;head:string;branch:string;title:string;body:string;draft:true;commits:{sha:string;subject:string;patch:string}[];stat:string;fingerprint:string};
export function publicationText(title:unknown,body:unknown){if(typeof title!=='string'||!title.trim()||title.length>200||typeof body!=='string'||body.length>12000)throw Error('Enter a PR title (up to 200 characters) and description (up to 12,000).');return {title:title.trim(),body};}
async function remoteRef(git:RepositoryGit,repo:string,url:string,branch:string,signal:AbortSignal){const out=await git(repo,['ls-remote','--heads',url,'refs/heads/'+branch],signal,true);if(!out)return null;const lines=out.split('\n');if(lines.length!==1||!new RegExp('^[a-f0-9]{40}\\t').test(out))throw Error('Could not verify remote branch.');return out.split('\t')[0];}
export async function previewPublication(options:{git:RepositoryGit;repo:string;task:string;head:string;base:string;title:string;body:string;approved:(sha:string,tree:string)=>boolean;signal:AbortSignal}){
 const {git,repo,signal,head}=options;if(!/^[a-f0-9]{40}$/.test(head)||!/^[a-f0-9-]{36}$/.test(options.task))throw Error('Invalid approved commit.');const base=branchName(options.base),branch='agentd/'+options.task;
 const destination=githubURL(await git(repo,['config','--get','remote.origin.url'],signal));if(base===branch)throw Error('Choose a different base branch.');
 if(await git(repo,['rev-parse','refs/heads/'+branch],signal)!==head)throw Error('The approved local branch changed. Review it before publishing.');
 await git(repo,['fetch','--no-tags','--no-recurse-submodules',destination,'refs/heads/'+base],signal,true,repo);const baseSha=await git(repo,['rev-parse','FETCH_HEAD^{commit}'],signal);
 if(await git(repo,['merge-base','--is-ancestor',baseSha,head],signal,false,undefined,true)==='NOT_ANCESTOR')throw Error('The GitHub base advanced or diverged. Update and review the changes against the current base before publishing.');
 const revisions=(await git(repo,['rev-list','--reverse',baseSha+'..'+head],signal)).split('\n').filter(Boolean);if(!revisions.length||revisions.length>20)throw Error('Publish between 1 and 20 reviewed commits at a time.');const commits=[];let size=0;
 for(const sha of revisions){const tree=await git(repo,['rev-parse',sha+'^{tree}'],signal);if(!options.approved(sha,tree))throw Error('Every outgoing commit must have passing checks and explicit local commit approval in this project.');
  const parents=(await git(repo,['rev-list','--parents','-n','1',sha],signal)).split(' ');if(parents.length!==2)throw Error('Merge commits are not supported in this publishing flow.');
  const names=(await git(repo,['diff','--name-only','-z','--no-renames',sha+'^',sha],signal)).split('\0');if(names.some(n=>/(^|\/)(\.env($|\.)|\.credentials\.json$|auth\.json$|id_(rsa|ed25519)$|\.npmrc$)|\.(pem|key)$/i.test(n)))throw Error('Outgoing history includes a sensitive filename. Resolve it before publishing.');
  const patch=await git(repo,['diff','--no-ext-diff','--no-textconv','--no-color','--no-renames',sha+'^',sha],signal);size+=Buffer.byteLength(patch);if(size>180000||patch.includes('Binary files '))throw Error('Outgoing history is too large or contains binary changes. This GUI cannot approve it.');
  commits.push({sha,subject:await git(repo,['show','-s','--format=%s',sha],signal),patch});
 }
 const existing=await remoteRef(git,repo,destination,branch,signal);if(existing&&existing!==head)throw Error('The remote publishing branch contains different work. It will not be overwritten.');
 const stat=await git(repo,['diff','--stat',baseSha,head],signal),fields={destination,base,baseSha,head,branch,...publicationText(options.title,options.body),draft:true as const,commits,stat};return {...fields,fingerprint:createHash('sha256').update(JSON.stringify(fields)).digest('hex')};
}
function verifiedPull(p:any,plan:PublishPlan){const slug=plan.destination.slice('https://github.com/'.length,-4);if(!Number.isSafeInteger(p?.number)||p.number<1||p.head?.sha!==plan.head||p.head?.ref!==plan.branch||p.base?.ref!==plan.base||p.head?.repo?.full_name?.toLowerCase()!==slug||p.base?.repo?.full_name?.toLowerCase()!==slug)throw Error('GitHub returned a different pull request. Inspect the repository before retrying.');return 'https://github.com/'+slug+'/pull/'+p.number;}
export async function executePublication(git:RepositoryGit,api:PullAPI,repo:string,plan:PublishPlan,signal:AbortSignal,checkpoint:(stage:string)=>void){
 if(githubURL(await git(repo,['config','--get','remote.origin.url'],signal))!==plan.destination||await git(repo,['rev-parse','refs/heads/'+plan.branch],signal)!==plan.head)throw Error('Publishing destination or local branch changed. Preview again.');
 if(await remoteRef(git,repo,plan.destination,plan.base,signal)!==plan.baseSha)throw Error('The GitHub base changed. Preview again before publishing.');
 const head=await remoteRef(git,repo,plan.destination,plan.branch,signal);if(head&&head!==plan.head)throw Error('Remote branch changed; it will not be overwritten.');
 const existing=await api(plan.destination,plan.branch,plan.base,null,signal);if(!Array.isArray(existing)||existing.length>1)throw Error('Ambiguous existing pull requests. Inspect GitHub before continuing.');if(existing.length)return {url:verifiedPull(existing[0],plan),reused:true};
 if(!head){checkpoint('pushing');await git(repo,['push','--porcelain','--no-follow-tags','--recurse-submodules=no','--force-with-lease=refs/heads/'+plan.branch+':',plan.destination,plan.head+':refs/heads/'+plan.branch],signal,true);}
 checkpoint('branch_published');if(await remoteRef(git,repo,plan.destination,plan.branch,signal)!==plan.head)throw Error('Could not confirm the published branch. Preview again to reconcile.');
 if(await remoteRef(git,repo,plan.destination,plan.base,signal)!==plan.baseSha)throw Error('Base changed after the branch was published. Preview again before creating a PR.');
 checkpoint('creating_pr');const result=await api(plan.destination,plan.branch,plan.base,{title:plan.title,body:plan.body},signal);if(result?.draft!==true||result?.base?.sha!==plan.baseSha)throw Error('GitHub created a PR with a changed base or draft state. Inspect GitHub before continuing.');return {url:verifiedPull(result,plan),reused:false};
}
